name: GRM-ggnn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.8
  - rdkit
  - networkx=2.4
  - matplotlib
  - pip
  - mlflow
  - sklearn
  - seaborn
  - numpy
  - pip:
    - pm4py
    - joblib
    - uuid
    - statistics
    - xgboost
    - tensorflow=1.3.0
    - os